<section class="max-w-7xl mx-auto space-y-7">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-xs font-semibold tracking-[0.16em] text-emerald-700 uppercase">Marketplace management</p><h1 class="mt-1 text-3xl font-bold text-slate-900">Shops</h1><p class="mt-1 text-sm text-slate-500">Create a shop and set its address before assigning shop users.</p></div>
        <x-button label="Add shop" icon="o-plus" class="btn-primary" wire:click="create" />
    </div>

    <x-card shadow>
        <div class="mb-4 flex items-center justify-between"><h2 class="font-semibold text-slate-800">Registered shops</h2><span class="text-sm text-slate-500">{{ $shops->count() }} {{ Str::plural('shop', $shops->count()) }} registered</span></div>
        <x-table :headers="$headers" :rows="$shops" striped>
            @scope('cell_name', $shop)<div class="font-medium text-slate-900">{{ $shop->name }}</div><small class="text-slate-500">{{ $shop->email }}</small>@endscope
            @scope('cell_owner', $shop)<div>{{ $shop->owner }}</div><small class="text-slate-500">{{ $shop->contact_number }}</small>@endscope
            @scope('cell_location', $shop)<div>{{ $shop->location }}</div><small class="text-slate-500">{{ $shop->city }}, {{ $shop->tole }}</small>@endscope
            @scope('cell_status', $shop)<span class="badge {{ $shop->status === 'active' ? 'badge-success' : 'badge-warning' }}">{{ ucfirst($shop->status) }}</span>@endscope
            @scope('actions', $shop)<div class="flex justify-end gap-1"><x-button icon="o-pencil-square" tooltip-left="Edit shop" wire:click="edit({{ $shop->id }})" class="btn-ghost btn-sm text-emerald-700" /><x-button icon="o-trash" tooltip-left="Delete shop" wire:click="confirmDelete({{ $shop->id }})" class="btn-ghost btn-sm text-error" /></div>@endscope
        </x-table>
    </x-card>

    <x-modal wire:model="shopModal" title="{{ $shopId ? 'Edit shop' : 'Create shop' }}" subtitle="{{ $shopId ? 'Update the shop details below.' : 'A login account will be created for this shop.' }}" separator box-class="max-w-5xl">
        <form wire:submit="save" class="grid gap-x-6 gap-y-5 md:grid-cols-2 xl:grid-cols-3" x-data>
            <label class="block"><span class="form-label">Shop name <span class="text-rose-600">*</span></span><input wire:model.live.debounce.300ms="name" class="form-input" placeholder="e.g. Himalayan Mart">@error('name') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">Owner <span class="text-rose-600">*</span></span><input wire:model.live.debounce.300ms="owner" class="form-input" placeholder="Owner's full name">@error('owner') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">Primary contact <span class="text-rose-600">*</span></span><input wire:model="contact_number" type="number" class="form-input number-input" placeholder="98XXXXXXXX">@error('contact_number') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">PAN number</span><input wire:model="pan_number" type="number" class="form-input number-input" placeholder="Optional PAN number">@error('pan_number') <small class="form-error">{{ $message }}</small> @enderror</label>
            <div class="block"><span class="form-label">Shop image</span><div class="flex items-center gap-3"><div class="h-16 w-16 shrink-0 overflow-hidden rounded-lg bg-slate-100">@if ($image)<img src="{{ $image->temporaryUrl() }}" class="h-full w-full object-cover" alt="Shop image preview">@elseif ($existingShopImage)<img src="{{ asset('storage/' . $existingShopImage) }}" class="h-full w-full object-cover" alt="Current shop image">@else<img src="{{ asset('default/vendor.svg') }}" class="h-full w-full object-cover" alt="Shop image placeholder">@endif</div><input wire:model="image" type="file" accept="image/*" class="block w-full text-sm text-slate-600"></div>@error('image') <small class="form-error">{{ $message }}</small> @enderror</div>
            <label class="block"><span class="form-label">Province <span class="text-rose-600">*</span></span><div wire:ignore><select class="province-select form-input"><option value="">Select province</option></select></div>@error('province_id') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">District <span class="text-rose-600">*</span></span><div wire:ignore><select class="district-select form-input"><option value="">Select district</option></select></div>@error('district_id') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">City <span class="text-rose-600">*</span></span><input wire:model="city" class="form-input" placeholder="City">@error('city') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">Tole / street <span class="text-rose-600">*</span></span><input wire:model="tole" class="form-input" placeholder="Tole or street">@error('tole') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">Email <span class="text-rose-600">*</span></span><input wire:model="email" type="email" class="form-input" placeholder="shop@example.com">@error('email') <small class="form-error">{{ $message }}</small> @enderror</label>
            <label class="block"><span class="form-label">Status <span class="text-rose-600">*</span></span><select wire:model="status" class="form-input"><option value="active">Active</option><option value="inactive">Inactive</option><option value="suspended">Suspended</option></select></label>
            @if (!$shopId)<div class="rounded-xl border border-emerald-100 bg-emerald-50/40 p-5 md:col-span-2 xl:col-span-3"><h3 class="font-semibold text-slate-800">Shop User</h3><p class="mt-1 text-xs text-slate-500">A login account is created automatically with this shop.</p><div class="mt-4 grid gap-x-6 gap-y-5 md:grid-cols-3"><label class="block"><span class="form-label">Name</span><input value="{{ $owner }}" readonly class="form-input bg-slate-100!" placeholder="Copied from owner"></label><label class="block"><span class="form-label">Username</span><input value="{{ $this->generatedUsernamePreview }}" readonly class="form-input bg-slate-100! text-slate-500"></label><label class="block"><span class="form-label">Password <span class="text-rose-600">*</span></span><input wire:model="shop_user_password" type="password" class="form-input" placeholder="Minimum 8 characters">@error('shop_user_password') <small class="form-error">{{ $message }}</small> @enderror</label></div></div>@endif
            <x-slot:actions><x-button label="Cancel" icon="o-x-mark" wire:click="closeShopModal" /><x-button label="{{ $shopId ? 'Save changes' : 'Create shop' }}" icon="o-check" wire:click="save" class="btn-primary" spinner="save" /></x-slot:actions>
        </form>
    </x-modal>

    <x-modal wire:model="deleteModal" title="Delete shop" separator><p class="text-slate-600">Are you sure? This action cannot be undone.</p><x-slot:actions><x-button label="Cancel" icon="o-x-mark" wire:click="$set('deleteModal', false)" /><x-button label="Delete shop" icon="o-trash" wire:click="deleteShop" class="btn-error" spinner="deleteShop" /></x-slot:actions></x-modal>
</section>

@script
<script>
Alpine.store('adminShopSetup',{shopData:@json(['province_id'=>$province_id,'district_id'=>$district_id]),init(){Alpine.nextTick(()=>this.initializeSelect2());window.addEventListener('shop-form-loaded',e=>this.loadShopLocation(e.detail));},initializeSelect2(){[{selector:'.province-select',key:'province_id',placeholder:'Select province',module:'get_province'},{selector:'.district-select',key:'district_id',placeholder:'Select district',module:'get_district'}].forEach(c=>this.initSelect2Element(c));},initSelect2Element(c){const e=$(c.selector);if(e.data('select2'))e.select2('destroy');e.select2({placeholder:c.placeholder,allowClear:true,dropdownParent:e.closest('.modal'),ajax:{url:`{{ route('searchSelect2', ['module' => 'MODULE']) }}`.replace('MODULE',c.module),delay:250,data:p=>({term:p.term,selected_id:c.key==='district_id'?this.shopData.province_id:this.shopData[c.key]}),processResults:d=>({results:Array.isArray(d)?d:(d.results||[])})}}).on('select2:select',v=>this.updateSelectedData(c.key,v.params.data.id)).on('select2:clear',()=>this.updateSelectedData(c.key,null));},updateSelectedData(k,v){this.shopData[k]=v||null;if(k==='province_id'){this.shopData.district_id=null;$('.district-select').val(null).trigger('change.select2');$wire.set('district_id',null);}$wire.set(k,this.shopData[k]);},loadShopLocation({province,district}){this.shopData.province_id=province?.id||null;this.shopData.district_id=district?.id||null;this.setSelect2Value('.province-select',province);this.setSelect2Value('.district-select',district);},setSelect2Value(s,o){const e=$(s);if(o&&!e.find(`option[value="${o.id}"]`).length)e.append(new Option(o.text,o.id,true,true));e.val(o?.id||null).trigger('change.select2');}});
</script>
@endscript

<style>.form-label{display:block;margin-bottom:.375rem;font-size:.875rem;font-weight:500;color:#334155}.form-input{width:100%;border:1px solid #cbd5e1;border-radius:.5rem;background:#fff;padding:.625rem .75rem;color:#0f172a;outline:none}.form-input:focus{border-color:#059669;box-shadow:0 0 0 3px rgb(16 185 129 / .12)}.number-input::-webkit-outer-spin-button,.number-input::-webkit-inner-spin-button{margin:0;-webkit-appearance:none}.number-input[type=number]{-moz-appearance:textfield}.form-error{display:block;margin-top:.35rem;color:#e11d48}.select2-container{width:100%!important}.select2-container--default .select2-selection--single{position:relative;display:flex;align-items:center;height:42px;border:1px solid #cbd5e1;border-radius:.5rem;background:#fff;padding:0 .75rem}.select2-container--default .select2-selection--single .select2-selection__rendered{width:100%;padding:0 2rem 0 0;color:#0f172a}.select2-container--default .select2-selection--single .select2-selection__clear{position:absolute;top:50%;right:.75rem;margin:0;color:#64748b;font-size:1.25rem;line-height:1;transform:translateY(-50%)}.select2-container--default .select2-selection--single .select2-selection__arrow{display:none}.select2-dropdown{border:1px solid #cbd5e1;border-radius:.5rem}.select2-container--open{z-index:60}</style>
